# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-15 02:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admissionsforms',
            fields=[
                ('sid', models.IntegerField(primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=12)),
                ('indate', models.DateField()),
                ('inscore', models.DecimalField(decimal_places=2, max_digits=8)),
                ('agent', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'admissionsforms',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bookborrow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowdate', models.DateField()),
                ('returndate', models.DateField()),
                ('operator', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'bookborrow',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bookinfo',
            fields=[
                ('bid', models.IntegerField(primary_key=True, serialize=False)),
                ('bname', models.CharField(max_length=12)),
                ('author', models.CharField(max_length=12)),
                ('category', models.CharField(max_length=12)),
                ('publication', models.CharField(max_length=12)),
                ('pubdate', models.DateField()),
                ('bnum', models.IntegerField()),
                ('indate', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('intro', models.CharField(max_length=100)),
                ('operator', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'bookinfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Choosecur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
            ],
            options={
                'db_table': 'choosecur',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clazz',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=24)),
            ],
            options={
                'db_table': 'clazz',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('curid', models.IntegerField(primary_key=True, serialize=False)),
                ('curname', models.CharField(max_length=12)),
                ('examdate', models.DateField()),
                ('examtype', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'course',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('gid', models.IntegerField(primary_key=True, serialize=False)),
                ('gname', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'grade',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('uaccount', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('upwd', models.CharField(max_length=12)),
                ('uname', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'login',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('mid', models.AutoField(primary_key=True, serialize=False)),
                ('mname', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'major',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Teacherinfo',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('tname', models.CharField(max_length=12)),
                ('gender', models.CharField(max_length=5)),
                ('age', models.IntegerField()),
                ('married', models.CharField(max_length=12)),
                ('idnum', models.CharField(max_length=18)),
                ('politicstatus', models.CharField(max_length=10)),
                ('nation', models.CharField(max_length=12)),
                ('edu', models.CharField(max_length=12)),
                ('birthdate', models.DateField()),
                ('tel', models.CharField(max_length=11)),
                ('workdate', models.DateField()),
                ('description', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'teacherinfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Techcourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'techcourse',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stuinfo',
            fields=[
                ('sid', models.ForeignKey(db_column='sid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='index.Admissionsforms')),
                ('identitynum', models.CharField(db_column='identityNum', max_length=18)),
                ('gender', models.CharField(max_length=5)),
                ('birthdate', models.DateField()),
                ('address', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('tel', models.CharField(max_length=11)),
                ('politicstatus', models.CharField(max_length=12)),
                ('health', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'stuinfo',
                'managed': False,
            },
        ),
    ]
